name: covid-19-community 

channels:
  - conda-forge
  - anaconda
  - esri
  - bioconda

dependencies:
  - python=3.7
  - openjdk=11.0.1
  - jupyterlab=3
  - pandas
  - dask
  - aiohttp
  - requests
  - xlrd
  - openpyxl
  - matplotlib
  - matplotlib-venn
  - seaborn=0.11.0
  - biopython
  - papermill=2.1.0
  - ipywidgets=7.6.2
  - scikit-learn=0.23.2
  - arcgis=1.8.1
  - bcbio-gff=0.6.6
  - geocoder
  - py3Dmol=0.8.0
  - unidecode
  - python-Levenshtein
  - pycountry
  - geopy
  - nodejs
  - plotly
  # - ipycytoscape>=1.0.3
  - pip
  - pip:
    - --pre
    - py2neo
    - git+https://github.com/pwrose/ipycytoscape.git 
