name: covid-19-community 

channels:
  - conda-forge
  - anaconda
  - esri

dependencies:
  - python=3.7
  - openjdk=11.0.1
  - jupyterlab=2.1.5
  - pandas
  - xlrd
  - matplotlib
  - seaborn=0.11.0
  - biopython
  - papermill=2.1.0
  - ipywidgets=7.5.1
  - arcgis=1.8.1
  - py3Dmol=0.8.0
  - pip
  - pip:
    - rcsbsearch==0.2.1
# use prerelease version of py2neo (required to select database by name)
# --pre seems to cause error on binder: list index out of range
#    - --pre
    - py2neo
